"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var BlockTransactionInfo;
(function (BlockTransactionInfo) {
    BlockTransactionInfo[BlockTransactionInfo["Hash"] = 0] = "Hash";
    BlockTransactionInfo[BlockTransactionInfo["Detail"] = 1] = "Detail";
    BlockTransactionInfo[BlockTransactionInfo["Receipt"] = 2] = "Receipt";
})(BlockTransactionInfo = exports.BlockTransactionInfo || (exports.BlockTransactionInfo = {}));
var METHODS;
(function (METHODS) {
    METHODS["PEER_COUNT"] = "peerCount";
    METHODS["BLOCK_NUMBER"] = "blockNumber";
    METHODS["SEND_RAW_TRANSACTION"] = "sendRawTransaction";
    METHODS["GET_BLOCK_BY_HASH"] = "getBlockByHash";
    METHODS["GET_BLOCK_BY_NUMBER"] = "getBlockByNumber";
    METHODS["GET_TRANSACTION_RECEIPT"] = "getTransactionReceipt";
    METHODS["GET_LOGS"] = "getLogs";
    METHODS["CALL"] = "call";
    METHODS["GET_TRANSACTION"] = "getTransaction";
    METHODS["GET_TRANSACTION_COUNT"] = "getTransactionCount";
    METHODS["GET_CODE"] = "getCode";
    METHODS["GET_ABI"] = "getAbi";
    METHODS["NEW_FILTER"] = "newFilter";
    METHODS["NEW_BLOCK_FILTER"] = "newBlockFilter";
    METHODS["UNINSTALL_FILTER"] = "uninstallFilter";
    METHODS["GET_FILTER_CHANGES"] = "getFilterChanges";
    METHODS["GET_FILTER_LOGS"] = "getFilterLogs";
    METHODS["GET_BALANCE"] = "getBalance";
    METHODS["GET_TRANSACTION_PROOF"] = "getTransactionProof";
    METHODS["METADATA"] = "getMetaData";
})(METHODS = exports.METHODS || (exports.METHODS = {}));
